// Human UI and WebMCP wrappers both call this small application layer.
export function createApp(config) {
  const repositoryUrl = 'https://github.com/twilighty-abhi/webmcp-gdg.git';
  const sourcePaths = config.sourcePaths || [config.sourcePath || `tracks/${config.slug}`];
  const cloneCommand = `git clone --filter=blob:none --sparse ${repositoryUrl} webmcp-gdg\ncd webmcp-gdg\ngit sparse-checkout set shared ${sourcePaths.join(' ')}\nnpm install\nnpm run dev`;
  const key = `webmcp-${config.slug}-state`;
  const saved = JSON.parse(localStorage.getItem(key) || '{}');
  const state = { items: Array.isArray(saved.items) ? saved.items : config.items.map(item => ({ ...item })), actions: Array.isArray(saved.actions) ? saved.actions : [], lastMessage: saved.lastMessage || '' };
  const persist = () => localStorage.setItem(key, JSON.stringify(state));
  const byId = id => state.items.find(item => item.id === id);
  const search = (input = {}) => { const query = String(input.query || '').toLowerCase(); return state.items.filter(item => (!query || Object.values(item).join(' ').toLowerCase().includes(query)) && (config.filters || []).every(filter => !input[filter.name] || String(item[filter.name]) === String(input[filter.name]))); };
  const details = ({ id } = {}) => { const item = byId(id); return item ? { ok: true, item } : { ok: false, error: { code: 'NOT_FOUND', message: `${config.singular} not found`, id } }; };
  const checkAvailability = ({ id, guests = 1, time } = {}) => { const item = byId(id); if (!item) return { ok: false, error: { code: 'NOT_FOUND', message: 'Restaurant not found', id } }; const available = item.available !== false && Number(guests) <= (item.maxGuests || 8); return available ? { ok: true, available: true, message: `${item.name} can seat ${guests} at ${time || item.availability}.` } : { ok: false, available: false, error: { code: 'UNAVAILABLE', message: `${item.name} cannot accommodate that request.` } }; };
  const act = (input = {}) => {
    const item = byId(input.id); if (!item) return { ok: false, error: { code: 'NOT_FOUND', message: `${config.singular} not found`, id: input.id } };
    if (config.action === 'reservation') { const availability = checkAvailability(input); if (!availability.ok) return availability; item.reservations = (item.reservations || 0) + 1; }
    if (config.action === 'registration' || config.action === 'booking') { if (typeof item.availableSeats === 'number' && item.availableSeats < 1) return { ok: false, error: { code: 'UNAVAILABLE', message: `${config.singular} is sold out` } }; if (typeof item.availableSeats === 'number') item.availableSeats -= 1; }
    if (config.action === 'cart-add') item.cartQuantity = (item.cartQuantity || 0) + Number(input.quantity || 1);
    if (config.action === 'completion') item.status = 'Completed';
    if (config.action === 'enrollment') item.enrolled = true;
    if (config.action === 'watchlist') item.watchlisted = true;
    const record = { id: `${config.action}-${Date.now()}`, itemId: item.id, at: new Date().toISOString(), ...input };
    state.actions.unshift(record); state.lastMessage = config.success(item); persist(); render(); return { ok: true, message: state.lastMessage, record, item };
  };
  const create = (input = {}) => { if (!config.createItem) return { ok: false, error: { code: 'UNSUPPORTED', message: `Creating ${config.plural.toLowerCase()} is not available.` } }; if (!String(input.name || '').trim()) return { ok: false, error: { code: 'INVALID_INPUT', message: 'A task title is required.' } }; const item = config.createItem(input); state.items.unshift(item); state.lastMessage = `${item.name} was created.`; persist(); render(); return { ok: true, item, message: state.lastMessage }; };
  const root = document.querySelector('#app');
  function render() {
    const filters = config.filters || [{ name: 'category', label: 'Category', options: [...new Set(state.items.map(item => item.category))] }];
    root.innerHTML = `<main class="shell"><nav class="nav"><span class="brand">${config.icon} ${config.brand}</span><span class="tag">Human-first starter site</span></nav><section class="hero"><h1>${config.headline}</h1><p>${config.subhead}</p></section><section class="panel clone-panel"><h2>Clone this page only</h2><p class="muted">Repository: <a href="${repositoryUrl}" target="_blank" rel="noreferrer">${repositoryUrl}</a></p><code>${cloneCommand}</code></section><div class="layout"><section>${config.createFields ? `<form id="create-form" class="panel"><strong>Create a task</strong><div class="toolbar">${config.createFields.map(field => `<input required name="${field.name}" placeholder="${field.placeholder}">`).join('')}<button>Create task</button></div></form>` : ''}<div class="toolbar"><input id="search" aria-label="Search" placeholder="Search ${config.plural.toLowerCase()}…">${filters.map(filter => `<select id="filter-${filter.name}"><option value="">All ${filter.label.toLowerCase()}</option>${filter.options.map(option => `<option value="${option}">${option}</option>`).join('')}</select>`).join('')}</div><div id="results" class="card-grid"></div></section><aside class="panel sticky"><h2>${config.actionTitle}</h2><p class="muted">Choose an item to continue.</p><div id="detail" class="empty">Nothing selected yet.</div>${state.lastMessage ? `<p class="notice">${state.lastMessage}</p>` : ''}<h3>Recent activity</h3><div class="muted">${state.actions.length ? state.actions.slice(0,3).map(action => `${byId(action.itemId)?.name || action.itemId} · ${new Date(action.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`).join('<br>') : 'No changes yet.'}</div></aside></div></main>`;
    const results = root.querySelector('#results');
    const draw = () => { const input = { query: root.querySelector('#search').value }; filters.forEach(filter => input[filter.name] = root.querySelector(`#filter-${filter.name}`).value); const list = search(input); results.innerHTML = list.length ? list.map(item => `<article class="card"><span class="pill">${item.category}</span><h3>${item.name}</h3><p class="muted">${item.description}</p><div class="meta">${Object.entries(item).filter(([key]) => !['id','name','description','category'].includes(key)).slice(0,3).map(([key,value]) => `<span class="pill">${key.replace(/([A-Z])/g, ' $1')}: ${value}</span>`).join('')}</div><button data-id="${item.id}">View details</button></article>`).join('') : `<div class="empty">No ${config.plural.toLowerCase()} match that search.</div>`; };
    results.onclick = event => { const id = event.target.dataset.id; if (!id) return; const item = byId(id), detail = root.querySelector('#detail'); detail.innerHTML = `<h3>${item.name}</h3><p class="muted">${item.description}</p><form id="action-form">${config.formFields.map(field => `<label class="muted">${field.label}<input required name="${field.name}" placeholder="${field.placeholder || ''}"></label><br>`).join('')}${config.action === 'reservation' ? '<button type="button" id="availability">Check availability</button> ' : ''}<button>${config.actionTitle}</button></form><div id="status"></div>`; detail.querySelector('#action-form').onsubmit = event => { event.preventDefault(); const result = act({ id, ...Object.fromEntries(new FormData(event.target)) }); if (!result.ok) detail.querySelector('#status').innerHTML = `<p class="notice error">${result.error.message}</p>`; }; detail.querySelector('#availability')?.addEventListener('click', () => { const result = checkAvailability({ id, ...Object.fromEntries(new FormData(detail.querySelector('form'))) }); detail.querySelector('#status').innerHTML = `<p class="notice ${result.ok ? '' : 'error'}">${result.ok ? result.message : result.error.message}</p>`; }); };
    root.querySelector('#search').oninput = draw; filters.forEach(filter => root.querySelector(`#filter-${filter.name}`).onchange = draw); root.querySelector('#create-form')?.addEventListener('submit', event => { event.preventDefault(); create(Object.fromEntries(new FormData(event.target))); }); draw();
  }
  render(); return { state, search, details, act, create, checkAvailability, render };
}
